library_ruina/catalog/urls.py
from . import views
from django.urls import re_path, path, include

books_patterns = [
    path("", views.BookListView.as_view(), name="books"),
    re_path(r"^create/$", views.BookCreateView.as_view(), name="book-create"),
    re_path(r"^(?P<pk>\d+)/update/$", views.BookUpdate.as_view(), name="book-update"),
    re_path(r"^(?P<pk>\d+)/delete/$", views.BookDelete.as_view(), name="book-delete"),
]

author_patterns = [
    re_path(r"^create/$", views.AutorCreateView.as_view(), name="author-create"),
    re_path(r"^(?P<pk>\d+)/update/$", views.AutorUpdate.as_view(), name="author-update"),
    re_path(r"^(?P<pk>\d+)/delete/$", views.AutorDelete.as_view(), name="author-delete"),
]

urlpatterns = [
    re_path(r"^$", views.index, name="index"),
    re_path(r"^authors$", views.AutorListView.as_view(), name="authors"),
    re_path(r"^mybooks/$", views.LoanedBooksByUserListView.as_view(), name="my-borrowed"),
    re_path(r"^book/(?P<pk>\d+)$", views.BookDetailView.as_view(), name="book-detail"),
    re_path(r"^authors/(?P<pk>\d+)$", views.AutorDetailView.as_view(), name="author-detail"),
    re_path(r"^allborrowed/$", views.AllBorrowedListView.as_view(), name="all-borrowed"),
    re_path(r'^book/(?P<pk>[-\w]+)/renew/$', views.renew_book_librarian, name="renew-book-librarian"),
    path("author/", include(author_patterns)),
    path("books/", include(books_patterns)),
]

library_ruina/library_ruina/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
#только на период разработки
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path("blog/", include('blog.url')),
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
    path("accounts/", include("django.contrib.auth.urls")),
    path("api/v1/", include("integration.urls")),

]
#только на период разработки
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library_ruina/blog/models.py
from django.db import models
import datetime
from django.urls import reverse
from django.contrib.auth.models import User


def actual_date():
    return datetime.datetime.now()


class Blogger(models.Model):
    """Модель данных блогера"""

    name = models.CharField(max_length=100, help_text="Enter a name blogger")
    description = models.TextField(max_length=2000, help_text="Enter a description of blogger")
    create_date = models.DateTimeField(default=actual_date, blank=True, null=True)

    class Meta:
        ordering = ["create_date"]
        permissions = (("can_add_blog", "Blogs moder"),)

    def get_absolute_url(self):
        return reverse("blogger-detail", args=[str(self.id)])

    def __str__(self):
        return self.name


class Blog(models.Model):
    """Модель поста в блоге"""

    title = models.CharField(max_length=100)
    context = models.TextField(max_length=2000)
    create_date = models.DateTimeField(default=actual_date, blank=True, null=True)
    blogger = models.ForeignKey(Blogger,
                                on_delete=models.SET_NULL,
                                null=True)

    class Meta:
        ordering = ["create_date"]

    def get_absolute_url(self):
        return reverse("blog-detail", args=[str(self.id)])

    def get_comment_url(self):
        return reverse("create-comment", args=[str(self.id)])

    def __str__(self):
        return self.title


class Comment(models.Model):
    """Модель хранит комментарий к посту в блоге """

    text = models.TextField(max_length=1000)
    blog = models.ForeignKey(Blog, on_delete=models.SET_NULL, null=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    create_date = models.DateTimeField(default=actual_date, blank=True, null=True)

    class Meta:
        ordering = ["create_date"]
        permissions = (("can_delete_comment", "Comment moder"),)


    def __str__(self):
        return "%s, %s" % (self.user, self.create_date)

library_ruina/blog/views.py
from django.shortcuts import render
from .models import Blogger, Blog, Comment
from django.contrib.auth.decorators import login_required, permission_required
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy

import logging

from integration.exception import BaseExceptions, base_exception

logger = logging.getLogger(__name__)


@base_exception
@login_required()
def index_blog(request):
    """Представление, выводящая статистику блога"""

    num_blogs = Blog.objects.all().count()
    num_bloggers = Blogger.objects.all().count()
    return render(request, 'index_blog.html', context={
        "num_blogs": num_blogs,
        "num_bloggers": num_bloggers,
    })


class BloggerListViews(LoginRequiredMixin, BaseExceptions, generic.ListView):
    """Список блогеров в блоге"""

    model = Blogger
    template_name = "blog/blogger_list.html"
    context_object_name = "bloggers_list"
    paginate_by = 5


class BlogListViews(LoginRequiredMixin, BaseExceptions, generic.ListView):
    """Список всех блогов"""

    model = Blog
    template_name = "blog/blog_list.html"
    paginate_by = 5
    context_object_name = "blog_list"


class BlogDetailView(LoginRequiredMixin, BaseExceptions, generic.DetailView):
    """Представление заметки в блоге"""

    model = Blog
    template_name = "blog/blog_detail.html"
    context_object_name = "blog"


class BloggerDetailView(LoginRequiredMixin, BaseExceptions, generic.DetailView):
    """Представление блогера"""

    model = Blogger
    template_name = "blog/blogger_detail.html"
    context_object_name = "blogger"


class CommentCreateView(LoginRequiredMixin, BaseExceptions, CreateView):
    """Представление создания комментария"""

    model = Comment
    fields = ["text"]
    template_name = "blog/create_comment.html"

    def get_success_url(self):
        return reverse_lazy("blog-detail", args=self.kwargs.get('pk'))

    def form_valid(self, form):
        user = self.request.user
        blog = Blog.objects.get(id=self.kwargs.get('pk'))
        form.instance.user = user
        form.instance.blog = blog
        return super(CommentCreateView, self).form_valid(form)


class CommentDeleteView(PermissionRequiredMixin, BaseExceptions, DeleteView):
    """Представление удаления комментария"""

    permission_required = ("catalog.can_delete_comment",)
    model = Comment
    template_name = "blog/comment_delete.html"
    context_object_name = "comment"

    def get_success_url(self):
        comment = Comment.objects.get(id=self.kwargs.get('pk'))
        pk = comment.blog.pk
        return reverse_lazy("blog-detail", kwargs={"pk": pk})


class BlogCreateView(LoginRequiredMixin, BaseExceptions, CreateView):
    """Создание заметки в блоге"""

    model = Blog
    template_name = "blog/blog_form.html"
    fields = ["title", "context", "blogger"]


class BlogUpdateView(LoginRequiredMixin, BaseExceptions, UpdateView):
    """Обновление заметки в блоге"""

    model = Blog
    template_name = "blog/blog_form.html"
    fields = ["title", "context"]


class BlogDeleteView(LoginRequiredMixin, BaseExceptions, DeleteView):
    """Удаление заметки из блога"""

    model = Blog
    template_name = "blog/blog_delete.html"
    context_object_name = 'blog'
    success_url = reverse_lazy("blogs")

library_ruina/blog/templates/blog/blog_delete.html
{% extends "base_blog_template.html" %}

{% block content %}

<h1>Delete blog</h1>

<p>Are you sure you want to delete blog: {{ blog.title }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete." />
</form>

{% endblock %}

library_ruina/blog/templates/blog/blog_detail.html
{% extends "base_blog_template.html" %}

{% block content %}
  <h1>{{ blog.title }}</h1>
    {% if perms.catalog.can_add_blog %}
      <p>
        <a href="{% url 'blog-update' blog.pk %}">Update</a>
        <a href="{% url 'blog-delete' blog.pk %}">Delete</a>
      </p>
    {% endif %}
  <dev>
  <p><b>Create dates: </b>{{ blog.create_date }}</p>
  <p><b>Author: </b><a href="{{ blog.blogger.get_absolute_url }}">{{ blog.blogger.name }}</a></p>
  <p><b>Description: </b></p>
  <p> {{ blog.context }} </p>
    <div style="margin-left:20px;margin-top:20px">
      <h3>Comments</h3>

      {% for comment in blog.comment_set.all %}
      <hr>
      <p>
        {{ comment.user }} ({{ comment.create_date }}) - {{ comment.text }}
        {% if perms.catalog.can_delete_comment %}
          <a href=" {% url 'delete-comment' comment.id %} ">Delete</a>
        {% endif %}
      </p>
      {% endfor %}
      {% if user.is_authenticated %}
      <h4><a href="{{ blog.get_comment_url }}">Add comment</a></h4>
      {% endif %}

    </div>
  </dev>
{% endblock %}

library_ruina/blog/templates/blog/blog_form.html
{% extends "base_blog_template.html" %}

{% block content %}

{% if 'create' in request.path %}
<h1>Add blog</h1>
{% else %}
<h1> Update blog </h1>
{% endif %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}

library_ruina/blog/templates/blog/blog_list.html
{% extends "base_blog_template.html" %}


{% block content %}
    <h1>All Blogs</h1>

    {% if blog_list %}
    <ul>

      {% for blog in blog_list %}
      <li>
        <a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a>
          ({{ blog.create_date }}) - <a href="{{ blog.blogger.get_absolute_url }}">{{ blog.blogger }}</a>
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no bloggers in the BLOG.</p>
    {% endif %}
{% endblock %}

library_ruina/blog/templates/blog/blogger_detail.html
{% extends "base_blog_template.html" %}

{% block content %}
  <h1>Blogger: {{ blogger.name }}</h1>

  <p><strong>Create dates:</strong> {{ blogger.create_date }}</p>
  <p><strong>Count blogs: {{ blogger.blog_set.all.count }}</strong></p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Blogs</h4>

    {% for blog in blogger.blog_set.all %}
    <hr>
    <p><a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a> Post date: {{ blog.create_date }} </p>
    {% endfor %}
  </div>
{% endblock %}

library_ruina/blog/templates/blog/blogger_list.html
{% extends "base_blog_template.html" %}


{% block content %}
    <h1>All Bloggers</h1>

    {% if bloggers_list %}
    <ul>

      {% for blogger in bloggers_list %}
      <li>
        <a href="{{ blogger.get_absolute_url }}">{{ blogger.name }} Registration: {{ blogger.create_date }}</a>
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no bloggers in the BLOG.</p>
    {% endif %}
{% endblock %}

library_ruina/blog/templates/blog/comment_delete.html
{% extends "base_blog_template.html" %}

{% block content %}

<h1>Delete Book</h1>

<p>Are you sure you want to delete comment user: {{ comment.user }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete." />
</form>

{% endblock %}

library_ruina/blog/templates/blog/create_comment.html
{% extends "base_blog_template.html" %}

{% block content %}

{% if 'create' in request.path %}
<h1>Add comment</h1>
{% else %}
<h1> Update comment </h1>
{% endif %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}