library_ruina/catalog/urls.py
from . import views
from django.urls import re_path, path, include

books_patterns = [
    path("", views.BookListView.as_view(), name="books"),
    re_path(r"^create/$", views.BookCreateView.as_view(), name="book-create"),
    re_path(r"^(?P<pk>\d+)/update/$", views.BookUpdate.as_view(), name="book-update"),
    re_path(r"^(?P<pk>\d+)/delete/$", views.BookDelete.as_view(), name="book-delete"),
]

author_patterns = [
    re_path(r"^create/$", views.AutorCreateView.as_view(), name="author-create"),
    re_path(r"^(?P<pk>\d+)/update/$", views.AutorUpdate.as_view(), name="author-update"),
    re_path(r"^(?P<pk>\d+)/delete/$", views.AutorDelete.as_view(), name="author-delete"),
]

urlpatterns = [
    re_path(r"^$", views.index, name="index"),
    re_path(r"^authors$", views.AutorListView.as_view(), name="authors"),
    re_path(r"^mybooks/$", views.LoanedBooksByUserListView.as_view(), name="my-borrowed"),
    re_path(r"^book/(?P<pk>\d+)$", views.BookDetailView.as_view(), name="book-detail"),
    re_path(r"^authors/(?P<pk>\d+)$", views.AutorDetailView.as_view(), name="author-detail"),
    re_path(r"^allborrowed/$", views.AllBorrowedListView.as_view(), name="all-borrowed"),
    re_path(r'^book/(?P<pk>[-\w]+)/renew/$', views.renew_book_librarian, name="renew-book-librarian"),
    path("author/", include(author_patterns)),
    path("books/", include(books_patterns)),
]

library_ruina/library_ruina/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
#только на период разработки
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path("blog/", include('blog.url')),
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
    path("accounts/", include("django.contrib.auth.urls")),
    path("api/v1/", include("integration.urls")),

]
#только на период разработки
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library_ruina/catalog/models.py
from django.db import models
from django.urls import reverse
import uuid
from django.contrib.auth.models import User
from datetime import date


def get_default_field_id():
    """Генерация uuid token"""

    return uuid.uuid4()


class Genre(models.Model):
    """Модель языков книг"""

    name = models.CharField(max_length=200, help_text="Enter a book genre (e.g. Science Fiction")

    def __str__(self):
        return self.name


class Language(models.Model):
    name = models.CharField(max_length=100,
                            help_text="Enter a language")

    def __str__(self):
        return self.name


class Autor(models.Model):
    """Модель содержит данные автора"""

    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField("died", null=True, blank=True)

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])

    class Meta:
        ordering = ["last_name"]

    def __str__(self):
        return "%s %s" % (self.last_name, self.first_name)


class Book(models.Model):
    """Модель содержит данные книги"""

    title = models.CharField(max_length=200)
    author = models.ForeignKey(Autor, on_delete=models.SET_NULL, null=True)
    genre = models.ManyToManyField(Genre, help_text="Select a genre")
    isbn = models.CharField("ISBN", max_length=13, help_text="ISBN number")
    summary = models.TextField(max_length=2000, help_text="Enter a brief description of the book")
    language = models.ForeignKey(Language, on_delete=models.SET_NULL, null=True)

    class Meta:
        ordering = ["isbn"]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        return ", ".join([genre.name for genre in self.genre.all()[:3]])
    display_genre.short_description = "Genre"


class BookInstance(models.Model):
    """Модель экземпляра книги, хранит данных о бронировании и бронирующем юзере"""
    id = models.UUIDField(primary_key=True, default=get_default_field_id,
                          help_text="Unique ID for this particular book across whole library")
    book = models.ForeignKey(Book, on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAD_STATUS = (
        ("m", "Maitenance"),
        ("o", "On load"),
        ("a", "Available"),
        ("r", "Reserved")
    )

    status = models.CharField(max_length=1, choices=LOAD_STATUS, default='m',
                              blank=True, help_text="Book availability")

    class Meta:
        ordering = ["due_back"]
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        return "%s: (%s)" % (self.id, self.book.title)

    @property
    def is_overdue(self):
        """Проверка валидности даты"""
        if self.due_back and date.today() > self.due_back:
            return True
        return False

library_ruina/catalog/forms.py
from django import forms
import datetime
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _


class RenewBookForm(forms.Form):
    """Форма принимает данные для корректировки бронирования"""

    renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks.")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        if data < datetime.date.today():
            raise ValidationError(_("Invalid date - renewal in past"))

        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_("Invalid date - renewal more than 4 weeks ahead"))

        return data

library_ruina/catalog/views.py
import datetime
import logging

from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required, permission_required
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy

from integration.exception import BaseExceptions, base_exception
from .models import Book, Autor, Genre, Language, BookInstance
from .forms import RenewBookForm


logger = logging.getLogger(__name__)


@base_exception
@login_required()
def index(request):
    """Главная страница с выводом статистики приложения"""

    num_books = Book.objects.all().count()
    num_instance = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(status__exact="a").count()
    num_authors = Autor.objects.all().count()
    num_genre = Genre.objects.all().count()
    num_language = Language.objects.all().count()
    classic_books = Book.objects.filter(genre__name="Classic").count()
    classic_book = Book.objects.filter(genre__name="Classic")
    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits + 1

    return render(request, 'index.html', context={
        "num_books": num_books,
        "num_instance": num_instance,
        "num_instances_available": num_instances_available,
        "num_authors": num_authors,
        "num_genre": num_genre,
        "num_language": num_language,
        "classic_books": classic_books,
        "classic_book": classic_book,
        "num_visits": num_visits,
    })


class BookListView(LoginRequiredMixin, BaseExceptions, generic.ListView):
    """Список всех книг в БД"""
    login_url = "/accounts/login/"
    redirect_field_name = "redirect_to"
    model = Book
    context_object_name = 'my_book_list'
    paginate_by = 2

    def get_context_data(self, **kwargs):
        context = super(BookListView, self).get_context_data(**kwargs)
        context['some_data'] = 'This is just some data'
        return context


class BookDetailView(BaseExceptions, generic.DetailView):
    """Вывод данных конкретной книги"""

    model = Book
    context_object_name = "book"


class AutorListView(BaseExceptions, generic.ListView):
    """Список авторов в системе"""

    model = Autor
    context_object_name = "list_author"
    paginate_by = 4


class AutorDetailView(BaseExceptions, generic.DetailView):
    """Вывод данных конкретного автора"""

    model = Autor
    context_object_name = "author"


class LoanedBooksByUserListView(BaseExceptions, LoginRequiredMixin, generic.ListView):
    """Список книг забронированный авторизованным пользователем"""

    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    context_object_name = "bookinstance_list"
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')


class AllBorrowedListView(BaseExceptions, PermissionRequiredMixin, generic.ListView):
    """Все забронированные книги"""

    permission_required = ('catalog.can_mark_returned', 'catalog.can_edit')
    model = BookInstance
    context_object_name = "allborrowed"
    template_name = "catalog/list_borrowed_user.html"
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact="o").order_by("due_back")


@permission_required("catalog.can_mark_returned")
def renew_book_librarian(request, pk):
    """Корректировка сделанного бронирования книги"""

    book_inst = get_object_or_404(BookInstance, pk=pk)

    if request.method == "POST":
        form = RenewBookForm(request.POST)

        if form.is_valid():
            book_inst.due_back = form.cleaned_data['renewal_date']
            book_inst.save()

            return HttpResponseRedirect(reverse("all-borrowed"))
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={"renewal_date": proposed_renewal_date,})

    return render(request, "catalog/book_renew_librarian.html", {"form": form,
                                                                 "bookinst": book_inst})


class AutorCreateView(BaseExceptions, PermissionRequiredMixin, CreateView):
    """Страница создания нового автора"""

    permission_required = ("catalog.can_mark_returned",)
    model = Autor
    fields = "__all__"
    initial = {"date_of_death": "12/10/2022",}
    template_name = "catalog/author_form.html"


class AutorUpdate(BaseExceptions, PermissionRequiredMixin, UpdateView):
    """Обновление даных автора"""

    permission_required = ("catalog.can_mark_returned",)
    model = Autor
    fields = ["first_name", "last_name", "date_of_birth", "date_of_death"]
    template_name = "catalog/author_form.html"


class AutorDelete(BaseExceptions, PermissionRequiredMixin, DeleteView):
    """Удаление автора"""

    permission_required = ("catalog.can_mark_returned",)
    model = Autor
    success_url = reverse_lazy('authors')
    template_name = "catalog/author_confirm_delete.html"


class BookCreateView(BaseExceptions, PermissionRequiredMixin, CreateView):
    """Создание книги"""

    permission_required = ("catalog.can_mark_returned",)
    model = Book
    fields = "__all__"
    template_name = "catalog/book_form.html"


class BookUpdate(BaseExceptions, PermissionRequiredMixin, UpdateView):
    """Обновление ланных книги"""

    permission_required = ("catalog.can_mark_returned",)
    model = Book
    fields = "__all__"
    template_name = "catalog/book_form.html"


class BookDelete(BaseExceptions, PermissionRequiredMixin, DeleteView):
    """Удаление книги"""

    permission_required = ("catalog.can_mark_returned",)
    model = Book
    success_url = reverse_lazy('books')
    template_name = "catalog/book_confirm_delete.html"

library_ruina/catalog/templates/catalog/author_confirm_delete.html
{% extends "base_template.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete." />
</form>

{% endblock %}

library_ruina/catalog/templates/catalog/author_form.html
{% extends "base_template.html" %}

{% block content %}

{% if 'create' in request.path %}
<h1>Add author</h1>
{% else %}
<h1> Update author </h1>
{% endif %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}

library_ruina/catalog/templates/catalog/autor_detail.html
{% extends "base_template.html" %}

{% block content %}
  <h1>Author: {{ author.last_name }}, {{ author.first_name }}</h1>

  {% if perms.catalog.can_mark_returned %}
    <p>
      <a href="{% url 'author-update' author.pk %}">Update</a> |
      <a href="{% url 'author-delete' author.pk %}">Delete</a>
    </p>
  {% endif %}

  <p><strong>Life dates:</strong> {{ author.date_of_birth }} - {{ author.date_of_death }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Books</h4>

    {% for book in author.book_set.all %}
    <hr>
    <p><a href="{{ book.get_absolute_url }}">{{ book.title }}</a> [{{ book.language }}] ({{ book.bookinstance_set.all.count }})</p>
    <p> {{ book.summary }} </p>
    {% endfor %}
  </div>
{% endblock %}

library_ruina/catalog/templates/catalog/autor_list.html
{% extends "base_template.html" %}


{% block content %}
    <h1>Author List</h1>

    {% if list_author %}
    <ul>

      {% for author in list_author %}
      <li>
        <a href="{{ author.get_absolute_url }}">{{ author.last_name }}, {{ author.first_name }}
            ({{ author.date_of_birth }} - {{ author.date_of_death }})</a>
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no authors in the library.</p>
    {% endif %}
{% endblock %}

library_ruina/catalog/templates/catalog/book_confirm_delete.html
{% extends "base_template.html" %}

{% block content %}

<h1>Delete Book</h1>

<p>Are you sure you want to delete the book: {{ book.title }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete." />
</form>

{% endblock %}

library_ruina/catalog/templates/catalog/book_detail.html
{% extends "base_template.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  {% if perms.catalog.can_mark_returned %}
    <p>
      <a href="{% url 'book-update' book.pk %}">Update</a> |
      <a href="{% url 'book-delete' book.pk %}">Delete</a>
    </p>
  {% endif %}

  <p><strong>Author:</strong> <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Language:</strong> {{ book.language }}</p>
  <p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

library_ruina/catalog/templates/catalog/book_form.html
{% extends "base_template.html" %}

{% block content %}
{% if 'create' in request.path %}
<h1>Add book</h1>
{% else %}
<h1> Update book </h1>
{% endif %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}

library_ruina/catalog/templates/catalog/book_list.html
{% extends "base_template.html" %}


{% block content %}
    <h1>Book List</h1>

    {% if my_book_list %}
    <ul>

      {% for book in my_book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no books in the library.</p>
    {% endif %}
{% endblock %}

library_ruina/catalog/templates/catalog/book_renew_librarian.html
{% extends "base_template.html" %}

{% block content %}

    <h1>Renew: {{bookinst.book.title}}</h1>
    <p>Borrower: {{bookinst.borrower}}</p>
    <p{% if bookinst.is_overdue %} class="text-danger"{% endif %}>Due date: {{bookinst.due_back}}</p>

    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form }}
        </table>
        <input type="submit" value="Submit" />
    </form>

{% endblock %}

library_ruina/catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_template.html" %}

{% block content %}
    <h1>User Borrowed List</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a> ({{ bookinst.due_back }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}

library_ruina/catalog/templates/catalog/list_borrowed_user.html
{% extends "base_template.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if allborrowed %}
    <ul>

      {% for borrowed in allborrowed %}
      <li class="{% if borrowed.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' borrowed.book.pk %}">{{ borrowed.book.title }}</a>
          ({{ borrowed.due_back }}) from user: {{ borrowed.borrower }}
          {% if perms.catalog.can_mark_returned %}- <a href="{% url 'renew-book-librarian' borrowed.id %}">Renew</a>  {% endif %}
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no borrowed.</p>
    {% endif %}
{% endblock %}